name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache .terraform directory
        uses: actions/cache@v3
        with:
          path: terraform-docker-project/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('terraform-docker-project/**/.terraform') }}

      - name: pwd
        run: pwd

      - name: ls
        run: ls -ltr

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false  # Or true, if you prefer

      - name: Navigate to Terraform Directory
        run: cd terraform-docker-project # Only needed if terraform_wrapper is false

      - name: Terraform Fmt
        run: terraform fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4  # Corrected to v4
        with:
          name: tfplan
          path: terraform-docker-project/

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: prod