name: Terraform CI/CD

on:
  push:
    branches:
      - main # Only run on pushes to main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List Files (Debug)
        run: ls -al

      - name: Navigate to Terraform Directory
        run: cd terraform-docker-project # Relative path!

      - name: List Files After Navigation (Debug)
        run: ls -al

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest # Or specify a version

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Plan Comment
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `#### Terraform Plan\n\`\`\`terraform\n${{ steps.plan.outputs.stdout }}\n\`\`\`\n`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false tfplan
        env:
          TF_VAR_environment: prod
