name: Terraform CI/CD

on:
  pull:
    branches:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List Files (Debug)
        run: ls -ltr

      - name: Navigate to Terraform Directory
        run: cd terraform-docker-project # Relative path!

      - name: List Files After Navigation (Debug)
        run: pwd
