name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache .terraform directory
        uses: actions/cache@v3
        with:
          path: ~/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/terraform.tf') }}

      - name: Navigate to Terraform Directory
        run: cd terraform-docker-project

      - name: Navigate to Terraform Directory
        run: pwd

      - name: Navigate to Terraform Directory
        run: ls -ltr

      - name: Terraform Format
        run: terraform fmt

      - name: tflint
        run: tflint

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply (on merge)
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: terraform apply tfplan

      - name: Configure AWS Credentials (Example)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
